var verify = require('adventure-verify')
var fs = require('fs')
var path = require('path')

exports.problem = fs.createReadStream(path.join(__dirname, 'problem.txt'))
exports.solution = fs.createReadStream(path.join(__dirname, 'solution.js'))

exports.verify = verify({ modeReset: true }, function (args, t) {
  t.plan(9)
  var f = require(path.resolve(args[0]))
  t.ok(f('az'), 'az')
  t.notOk(f('babbage'), 'babbage')
  t.notOk(f('AAA'), 'AAA')
  t.ok(f('123'), '123')
  t.ok(f('abc123'), 'abc123')
  t.notOk(f('Q1'), 'Q1')
  t.ok(f('under'), 'under')
  t.ok(f('404x'), '404x')
  t.ok(f('obelisk'), 'obelisk')
})
